ITSM-Project/SLASH-FE

src/components/layout/content/user/RequestSelectTop/RequestSelectTop.js, src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js, src/components/layout/content/user/requestManagement/RequestManagementContent.js, src/pages/contractManager/ContractManagerMain.js, src/pages/requestManager/RequestManagerMain.js, src/pages/user/RequestManagement.js, src/shared/Router.js
=> ♻️REFACTOR : 사용자의 요청 관리 탭 전체 구조 세팅

src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.css, src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js, src/components/layout/content/user/requestManagement/RequestManagementTop/RequestManagementTop.css, src/components/layout/content/user/requestManagement/RequestManagementTop/RequestManagementTop.js, src/styles/Content.css, src/styles/Label.css, src/styles/Sidebar.css
=> [STYLE] : User 요청관리 영역 css

src/components/feature/request/EditRequestForm.js, src/components/feature/request/select/RequestDetail.js, src/components/feature/request/select/RequestDetailForm.js, src/components/feature/request/select/RequestDetailInfoForm.css, src/components/feature/request/select/RequestDetailInfoForm.js, src/components/feature/request/select/RequestDetailModal.js, src/service/api/userService.js
=> [FEAT]: 요청 수정, 삭제 기능 구현

src/api/UserService.js, src/pages/login/Login.js
=> [FEAT] 계약 페이지 백 통신 Axios에 헤더 추가

src/api/UserService.js, src/components/layout/content/contractManager/contractManagerBottom/ContractManagerBottom.js, src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js, src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js, src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js, src/service/api/userService.js
=> [FIX]: 백통신 API 수정

src/api/UserService.js
=> [REFACTOR]: 업무 할당하기 api변경

src/components/labels/request/DueOneTimeLabel.js, src/components/labels/request/RequestLabel.js, src/components/layout/content/contractManager/RequestDetailContent.js, src/components/layout/content/contractManager/requestDetail/requestDetailBottom/RequestDetailBottom.js
=> [FEAT]: 할당하기 페이지에 요청 상세보기 컴포넌트 추가

src/components/layout/content/contractManager/contractManagerBottom/ContractManagerBottom.js, src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js, src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
- closes #80 
- 요청 관리 테이블에서 요청 상세 다 같이 나오는 부분 오류 수정이 부분과 요청 분류 필터링 부분은 아직 수정 중이고 나머지 위에 3가지 구현 내용은 반영되었습니다.(멘토링 일정 때문에 일단 구현된 부분까지 올리고 추후 계속 수정하겠습니다.)
=> [FIX]: 각종 오류 수정

.gitignore, package-lock.json, package.json, src/api/UserService.js, src/components/common/button/AssignmentButton.js, src/components/dropdown/Dropdown.css, src/components/labels/equipmentType/EquipmentTypeLabel.js, src/components/labels/processStatus/ProcessStatusLabel.js, src/components/labels/request/RequestLabel.js, src/components/layout/content/contractManager/contractManagerBottom/ContractManagerBottom.js, src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js, src/components/layout/content/user/UserMainContent.js, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.css, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.js, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.css, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js, src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.css, src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js, src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardToggle.css, src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js, src/shared/Router.js, src/styles/RequestManageBottom.css, src/styles/Sidebar.css
=> [FIX]: 멘토링 이후 수정 및 추가 사항

src/pages/login/Login.js, src/service/api/userService.js
=> [FIX]: 요청 관련 url 수정, 로그인 성공 응답 구조 수정

src/components/layout/content/requestManager/requestManagerTop/RequestManagerTop.js
=> [REFACTOR]: 요청매니저 메인 코드 리팩토링

src/components/feature/request/create/CreateRequest.js, src/service/api/userService.js
=> [REFACTOR]: 요청 생성 시 계약 아이디 넘겨주도록 수정

src/components/feature/table/ContractListTable.js, src/components/feature/table/GradeInputTable.js, src/components/feature/table/NoScoreGradeInputTable.js, src/components/layout/content/contractManager/contract/contractForm/ContractForm.css, src/components/layout/content/contractManager/contract/contractForm/ContractForm.js, src/styles/Common.css
=> [REFACTOR]: 계약 생성 및 조회 화면 UI 변경

src/api/UserService.js, src/components/feature/request/select/RequestDetailForm.js, src/components/feature/request/select/RequestDetailInfoForm.css, src/components/feature/request/select/RequestDetailInfoForm.js
=> [REFACTOR]: 할당하기 버튼 추가 및 로컬스토리지에 유저아이디 추가

src/components/common/header/ContractHeader.css, src/components/common/header/ContractHeaderV1.js, src/components/common/header/ContractHeaderV2.js
- closes #90 
-API는 수지언니가 올린 API로 수정만 해서 써주세요!
=> [FEAT]: 상단바 2가지 버전으로 구현

src/api/UserService.js, src/components/feature/request/select/RequestDetailForm.js, src/components/feature/request/select/RequestDetailInfoForm.css, src/components/feature/request/select/RequestDetailInfoForm.js, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.css, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js, src/pages/login/Login.js
=> [FEAT]: 통계 테이블 필터링

src/api/CommonService.js, src/api/ContractManagerService.js, src/components/dropdown/Dropdown.css, src/components/layout/content/contractManager/contractManagerMain/ContractManagerMain.css, src/components/layout/content/user/detailIndex/EvaluationDetailTable.js, src/components/layout/content/user/indexManagement/BottomTable.css, src/components/layout/sidebar/ContactManagerSidebar.js, src/components/layout/sidebar/UserSidebar.js, src/styles/CommonTable.css
=> [FIX]: merge 후 오류 해결

src/shared/Router.js
=> 🐛 FIX: 오류 수정

src/components/feature/chart/systemTypeChart/PieChart.css, src/components/layout/content/requestManager/requestManagerTop/RequestManagerTop.css, src/components/layout/content/user/requestManagement/RequestManagementTop/RequestManagementTop.css, src/styles/CommonTable.css, src/styles/RequestManageBottom.css
- closes #120 
- 보튼 세로 길이 줄임
- 표 그림자 제거
- 배경 박스 그림자 추가
- 외곽선 제거
- 외곽선 제거
- gap 줄임
=> [FEAT]: 통계 측정 결과 자세히 보기 css 수정, 요청 관리자 메인

src/components/dropdown/Dropdown.css, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.css, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.css, src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.css, src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js, src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardToggle.css, src/styles/RequestManageBottom.css
=> [FEAT]: 유저 메인 css 수정

src/components/feature/request/create/CreateRequest.js, src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
=> [FIX]: 요청 오류 수정

src/components/common/header/UserHeaderV1.js, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.css, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.js, src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
=> [FEAT]: 서비스 요청 적기 처리율 테이블 값 안나오는 오류 해결 및 초기날짜 현재날짜로 수정

src/components/feature/request/select/RequestDetailForm.js, src/components/feature/request/select/RequestDetailInfoForm.css, src/components/feature/request/select/RequestDetailInfoForm.js, src/components/labels/request/DueOneTimeLabel.js, src/components/layout/content/contractManager/requestAllocation/RequestAllocationTable.js, src/components/layout/content/contractManager/requestDetail/requestDetailBottom/RequestDetailBottom.js, src/components/layout/content/contractManager/statisticsResults/BottomTable.js, src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js, src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js, src/components/layout/content/user/requestManagement/RequestManagementTop/RequestManagementTop.js, src/shared/Router.js
=> [FEAT]: 할당하기 및 요청 처리 완료 오류 수정

src/api/CommonService.js, src/api/ContractManagerService.js, src/api/RequestManagerService.js, src/components/common/header/ContractHeaderV2.js, src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicatorEdit.js, src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicatorEditContent.js, src/components/layout/content/requestManager/RequestManagerMainContent.js, src/components/layout/content/requestManager/requestManagerTop/RequestManagerTop.js, src/components/layout/sidebar/ContactManagerSidebar.js, src/pages/contractManager/EstimateIndicatorEdit.js, src/shared/Router.js
=> [FEAT]: 요청 매니저 상단 연결

package-lock.json, package.json, src/components/common/header/YearHeader.css, src/components/common/header/YearHeader.js
=> [FEAT]: 연도 필터 헤더 컴포넌트 구현

src/components/feature/request/EditRequestForm.js, src/components/feature/request/RequestContentForm.css, src/components/feature/request/select/RequestDetailForm.js, src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js
- closes #160
- 요청 수정 기능 권한이 USER인 사람만 가능하게 해야하는데 추후에 token에서 꺼내서 쓰도록 변경하겠습니다~
=> [FIX]: 장애 적기 처리율 오류, 요청 수정 오류

src/api/UserService.js, src/components/feature/table/ StatisticsListTable.js, src/components/layout/content/contractManager/contract/contractForm/ContractListForm.css, src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.css, src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.js, src/components/layout/content/contractManager/statisticsResults/BottomTable.js, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartTable.css, src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.css, src/components/layout/content/user/indexManagement/BottomTable.js, src/pages/contractManager/StatisticsPdf.js, src/shared/Router.js
=> [REFACTO]: 지표 관리 페이지헤더 변경

src/api/CommonService.js, src/api/ContractManagerService.js, src/components/feature/table/IndicatorTable.js, src/components/layout/content/contractManager/statisticsResults/BottomTable.js, src/components/layout/content/contractManager/yearIndicator/YearIndicatorTable.js, src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js, src/pages/user/UserYearIndicator.js, src/shared/Router.js
=> [REFACTOR]: 지표관리 데이터 칼럼 변경 및 삭제 수정

src/api/UserService.js, src/components/feature/table/IndicatorTable.js, src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.js, src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicatorEdit.js, src/components/layout/content/contractManager/requestAllocation/RequestAllocationContent.js, src/components/layout/content/contractManager/requestAllocation/RequestAllocationTable.js, src/components/layout/content/requestManager/RequestManagerMainContent.js, src/components/layout/content/requestManager/RequestManagerStatusContent.js, src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js, src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js, src/components/layout/content/user/requestManagement/RequestManagementContent.js
=> [FIX]: 요청 관리 표 권한 별로 수정된 API에 따라 수정 & 종합지표 수정할 수 있도록 기능 구현 

src/api/UserService.js, src/components/feature/chart/GradeChart.js, src/components/feature/table/ StatisticsListTable.js, src/components/feature/table/EvaluationItemList.css, src/components/feature/table/IndicatorTable.js, src/components/feature/table/InputTable.js, src/components/labels/taskDetail/TaskDetailLabel.js, src/components/labels/taskType/TaskTypeLabel.js, src/components/layout/content/contractManager/contract/contractForm/ContractForm.js, src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicator.js, src/components/layout/content/contractManager/indicatorCalculator/EstimateIndicatorEdit.js, src/components/layout/content/contractManager/requestAllocation/RequestAllocationContent.js, src/components/layout/content/contractManager/requestAllocation/RequestAllocationTable.js, src/components/layout/content/contractManager/statisticsResults/MiddleIndex.js, src/components/layout/content/contractManager/yearIndicator/YearIndicatorTable.js, src/components/layout/content/requestManager/ContractInfo.js, src/components/layout/content/requestManager/RequestManagerMainContent.js, src/components/layout/content/requestManager/RequestManagerStatusContent.js, src/components/layout/content/requestManager/requestManagerBottom/RequestManagerBottom.js, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.css, src/components/layout/content/user/dashBoard/dashBoardBottom/ChartView.js, src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardBottom.js, src/components/layout/content/user/dashBoard/dashBoardBottom/DashBoardToggle.js, src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js, src/components/layout/content/user/requestManagement/RequestManagementContent.js, src/components/layout/sidebar/ContactManagerSidebar.js, src/styles/Content.css, src/styles/Login.css, src/styles/RequestManageBottom.css
=> [STYLE]: 차트 및 여러가지 CSS 수정

src/components/layout/content/user/requestManagement/RequestManagementBottom/RequestManageBottom.js
=> [FIX]: 계약 아이디 넘기도록 수정
